### ISSUE TITLE
ERC 721 Value

### ISSUE THREAD

**Issue by Adrianf23** [mickaelgermemont/AttendanceCoin#1]
- What can we put into the token to make it **valuable**?

- What other features do we want it to have?

**Comment by tesla809** [comment]
@Adrianf23 Special badges can be linked to GitHub projects we have worked on, times we came to class. Can show consistency to outside world beyond just meetup. Can be use in a Dapp that has all our profile pages.

We can add the work we did in the coin, say the contributors to x feature of project, or y project for a session. We can add Easter eggs with pass codes to prizes. Why do you guys think?

**Comment by Sampandu** [comment]
@tesla809 I agree. Showing contribution to a project would be helpful for those who is looking for a job.

**Comment by vutsalsinghal** [comment]
Merging with #26
