### ISSUE TITLE
Create Attendance Coin contract

### ISSUE THREAD

**Issue by mickaelgermemont** [mickaelgermemont/AttendanceCoin#11]
the goal is to create the AttendanceCoin!!

should we use that as our implementation?

[fixed-supply-erc20.sol](https://github.com/mickaelgermemont/AttendanceCoin/blob/master/ethereum/contract/fixed-supply-erc20.sol
)

also please share your rinkeby testnet address so we can create the pool of founders.

my address is 0x8c31cC3E155f9C4ef847F8C9968BAf87A90E7682

**Comment by mickaelgermemont** [comment]
we should also customize:     
line 118, symbol = "FIXED";
line 119, name = "Example Fixed Supply Token";

**Comment by vutsalsinghal** [comment]
@mickaelgermemont  address is network independent :wink: 

0x8fb092b0c5d80d1f4a1a0ff17d5a638afe24cfce

**Comment by mickaelgermemont** [comment]
yes, please share rinkeby testnet address, we will deploy the first test contract on rinkeby
