### ISSUE TITLE
Project directory structure

### ISSUE THREAD

**Issue by fodisi** [mickaelgermemont/AttendanceCoin#13]
I believe it's important to define the project directory structure (we need to think about third-party and internal libraries, third-party and internal contracts, unit testing, documentation, etc.). Maybe we should start with a default truffle directory structure. What are your thoughts on it? Or do you plan to use another tool/framework to develop the project?

**Comment by mickaelgermemont** [comment]
i agree project directory structure is important.

truffle directory? https://truffleframework.com/docs/truffle/getting-started/creating-a-project

have a project structure with the following items:
contracts/: Directory for Solidity contracts
migrations/: Directory for scriptable deployment files
test/: Directory for test files for testing your application and contracts
truffle.js: Truffle configuration file

is that what your suggestion is?

**Comment by mickaelgermemont** [comment]
i dont know much about Truffle. one thing would be to learn more about it. 
maybe one meetup assignment should be to look at it.

**Comment by fodisi** [comment]
Yes, you're right. The default Truffle directory is a good start. I'll submit a pull request with the basic repo, already initialized with truffle. Also, I'll attach an installation guide, so other participants can set up their environment with truffle and ganache.

But, in addition to the initial repository, maybe we should also discuss a better governance structure for the project directory, since the beginning of the project... For instance, currently, AttendanceCoint code is on the same folder as the external code (this is totally normal and OK for now and small projects, but if we plan to have this project growing on the long term, maybe we should separate our own code, from third-party code in different folders, etc.
