### ISSUE TITLE
get AttendanceCoin on testnet!

### ISSUE THREAD

**Issue by mickaelgermemont** [mickaelgermemont/AttendanceCoin#16]
share your eth address here and receive some AttendanceCoin on Rinkyby

Check all coin holders: https://rinkeby.etherscan.io/token/0x05e710afeebe27972e45f75aca2d16ec2c698f45#balances

**Comment by swellander** [comment]
0xbc148580f43b93aeea5ce7aa8e805bd6db13e8d1

**Comment by mickaelgermemont** [comment]
sent you 20! congrats! you were first ;-)

**Comment by swellander** [comment]
20AC received but still no transaction record on rinkeby etherscan. Any ideas why?

**Comment by JaberJanati** [comment]
0xd0c15fc18e640e4ca38b6cb2d61e274cd38057f4

**Comment by mickaelgermemont** [comment]
hey @swellander the etherscan transaction is https://rinkeby.etherscan.io/tx/0xa7fa3d673efc2c6174804af0c5454f559e886f3b2e2885ff589bd1b02fb904fc

**Comment by mickaelgermemont** [comment]
@JaberJanati i sent you 15AC! Congrats 2nd to post!

https://rinkeby.etherscan.io/tx/0x789d0b249a442dc5d3fc009befe2c5e9f2d05d7a9812a11c4cc24cca8898c7d6

**Comment by vutsalsinghal** [comment]
0x8b8ba03ed61ad1cb0e9befd0d02ecb444834887d

**Comment by fodisi** [comment]
0x78A3fECa82d62698c9912b66A06e5c035776DB90

**Comment by Alchemist21** [comment]
0xAB44ea3d9128d2B9eFd35DDeE0B58955a747c7F6

**Comment by mickaelgermemont** [comment]
@fodisi i sent you 13AC! Congrats 3nd to contribute!

https://rinkeby.etherscan.io/tx/0x8ed6a6414baca178f0910701560b63973b8193b8d6df3336c973a9a61165ecdd

**Comment by mickaelgermemont** [comment]
@Alchemist21 i sent you 11AC! Congrats 4th to contribute!

https://rinkeby.etherscan.io/tx/0x2e4ad8bbda87b1d81ee2520cac22c14dab4e8a4fe6af361454d29ce12f3cda91

**Comment by renegmed** [comment]
test comment to get ether 0x1b822f98ec5b54f7dc3c95d596f6bc82caa3078f

**Comment by mickaelgermemont** [comment]
@renegmed i sent you 10AC! Congrats 5th to contribute!

https://rinkeby.etherscan.io/tx/0x6788236cd6004b1f01ed24d98c440d56f860fa6fbd4c8ee406330ae0aa58a78b

**Comment by mickaelgermemont** [comment]
10AC to Chris!
https://rinkeby.etherscan.io/tx/0x6e16aeee0f80d9eaf82204c89dc896efa898741d9db23bbc98b77c022b8c8bc8

**Comment by laveradesign** [comment]
0x7d4a8Ee27a318e544b2c8939143EFf50838259E1 ready for some AC

**Comment by mickaelgermemont** [comment]
10AC to Lavera! 
https://rinkeby.etherscan.io/tx/0xa0c37b2b9e8cc7fa7303dc7ebab1a9406c960741e19956dfdd7f025b7ac9a1cb

**Comment by Alchemist21** [comment]
0xAB44ea3d9128d2B9eFd35DDeE0B58955a747c7F6

**Comment by vutsalsinghal** [comment]
@Alchemist21 Hey I sent you 10 AC!
0x137caee87447e277852c7a80df0391d4e57f7d7ef05e211af00a44e172b19481

**Comment by mickaelgermemont** [comment]
sent 10 AC to joshsantiago 
0xC409D4e2E884929ce476558b4db9D9b59D77534D

**Comment by vutsalsinghal** [comment]
this is Awesome guys! and now that we have faucet, I think it's safe to close this issue :D
