### ISSUE TITLE
Metamask balance not showing

### ISSUE THREAD

**Issue by Adrianf23** [mickaelgermemont/AttendanceCoin#17]
(On the rinkbey testnet, using the deployed address of 0x05e710afeebe27972e45f75aca2d16ec2c698f45):

When I add a custom token on metamask, I am not able to see my balance. I can see my balance and trandsfer coins on remix. Is there any way to do this in metamask?

**Comment by mickaelgermemont** [comment]
fixed! it was my bad. i sent the small unit possible, wei. AC has 18 decimals. just like 1 ETH is 1,000,000,000,000,000,000 wei

**Comment by mickaelgermemont** [comment]
can you confirm your balance now on metamask?

**Comment by fodisi** [comment]
Yes, it is working now. We can close this issue.

![image](https://user-images.githubusercontent.com/36540281/44211915-13f71300-a138-11e8-8964-9e534e031696.png)
