### ISSUE TITLE
Initial Value and Deployment

### ISSUE THREAD

**Issue by Adrianf23** [mickaelgermemont/AttendanceCoin#2]
- Will all the coins be pre-mined and distributed or do we want to continuously mint both coins?

**Comment by tesla809** [comment]
@mickaelgermemont @Adrianf23 Ummm. Well, what do you think? What are the merits of pre-mining some coins? Would it be a good idea to have a founder's pool? Say the initial people involved to have some extra coin and a special badge for being the founders?

Do we also want to cap the amount of total supply? Or only vote when we all agree to increase the supply? Or just have a fixed inflation rate? Or set a deflation rate?

**Comment by mickaelgermemont** [comment]
### talking about erc20-attendancecoin.
pre-mining some coins is easy to setup and easy to manage but it is a centralized management... as a first version of the AttendanceCoin i like this approach, at least we can get started quickly. that would be step 1.

founder's pool would be step 2. after creating the contract, the initial entire fund would be spread to some "founders"

if the supply is 1 billion i think thats a large amount. maybe it wont require minting... (just trying to keep things as simple as possible)

### talking about erc721-badge collectible. 
when we create that. we could plan for an initial "founders" badge distribution. that could give some incentive to contribute to the design.


what do you think?

**Comment by tesla809** [comment]
@mickaelgermemont I like the ideas. Lets get a lean MVP out quickly then we can focus on adding things in. Related to amount, we can pick a number that is feasible and easy to manage and reduce complexity.

The incentives question is a great point. How do we create incentives in the coins to get the behaviors that we want in the a) open source contributors b) any community that uses it later on, aka us ?

All the issues we run into now will be learning experiences for later.
