### ISSUE TITLE
Faucet for attendance coin on testnet

### ISSUE THREAD

**Issue by fodisi** [mickaelgermemont/AttendanceCoin#20]
Should we create a faucet to get Attendance Coin  on the test net? we'd need to update the contract and create an user interface or create an independent contract to serve as the faucet. This faucet contract would receive an initial balance, so it could give to any user that requests Attendance Coin (small drops of 1, 5, 10 AT per request).

**Comment by tesla809** [comment]
I like that idea. I will start to work that this Friday at the meetup.

**Comment by vutsalsinghal** [comment]
But the whole idea of AC was to: disburse coins only to those who deserve. If you implement faucet then _anyone_ can get AC ?!

**Comment by fodisi** [comment]
The faucet is only for the TEST NET, where it has no value. It wouldn't be deployed to the main net, where AC would be distributed based In meritocracy or any other distribution model to be defined.

**Comment by vutsalsinghal** [comment]
I don't think we'll even deploy it to mainnet.... So whatever significance they will have will be applicable when they are on testnet

**Comment by tesla809** [comment]
@vutsalsinghal You never know. This thing might pick up steam. We are talking about interesting ideas that can be used with the concept of attendance. Abstracting things bit, lets talk about the value of showing up to places, the value of knowledge networks, and the value of saving time on searching through profiles for recruitment of skills or persons or activation of people. 

Not to get too much into this in this issue (thats for the issue #15), we can quantify the value proper signaling (of a skill or attendance) via two metrics a badge and coin. It could be an interesting thought experiment or tool for application to say the least.

**Comment by mickaelgermemont** [comment]
a faucet on testnet is good for tests. and a good training. 
can we find a solution that does not require trashing the AC contract? how can we add feature and keep the current AC contract?

i think one way is to create and deploy a faucet contract. i will transfer lots of AC to the faucet address. that way the faucet will have a big AC balance =D. the faucet would have a method to send AC (it will interact with the AC contract and use the transfer method) to whoever request it. The method does not need any arguments. we can say the faucet distributes 10AC to msg.sender
what do you think?

btw 10AC == 10 000 000 000 000 000 000
just like 10eth == 10 000 000 000 000 000 000 wei

**Comment by mickaelgermemont** [comment]
```
contract ACFaucet {
   function distribute() {
      acContract.send(msg.sender, 10AC)
   }
}
```

**Comment by fodisi** [comment]
Just to let you guys know, I'm writing the Faucet contract. I'll PR as soon as it is ready.

**Comment by vutsalsinghal** [comment]
@fodisi will this do?
https://github.com/mickaelgermemont/AttendanceCoin/blob/feature_faucet/contracts/attendancecoin-erc20.sol#L256-L291
