### ISSUE TITLE
Bug in the contract balance function?

### ISSUE THREAD

**Issue by fodisi** [mickaelgermemont/AttendanceCoin#23]
I believe our contract has some bug in one (or more) of our functions related to balances (balanceOf, and transfers).
Using our contracts balanceOf(address) function for my address I get a result of 13 AC tokens. However looking on Rinkeby-Etherscan, my balance is actually "0.000000000000000013".

Maybe this is also the reason why our token balance does not show on Metamask (which only shows 4 decimal places).

I'll investigate this more on the weekend, but maybe someone has a spare time to take a look at it.

![ac-rinkeby-etherscan-balances](https://user-images.githubusercontent.com/36540281/44182484-2c821180-a0d5-11e8-83d2-e564137964a7.PNG)

**Comment by mickaelgermemont** [comment]
it seems i have been using it wrong. i sent wei

1 AC = 1,000,000,000,000,000,000 wei

**Comment by mickaelgermemont** [comment]
congrats @fodisi i increased your AC balance! +14AC ;-)
