### ISSUE TITLE
Curate a list of small Dapp projects that we could build to learn the fundamentals of Blockchain Development 

### ISSUE THREAD

**Issue by chrisauinmotion** [mickaelgermemont/AttendanceCoin#27]
Let us put together a list of Dapp projects that will support our efforts in learning Blockchain development.

Add any tutorials or Dapp project ideas to this issue.

**Comment by mickaelgermemont** [comment]
@chrisauinmotion  what do you think of https://github.com/mickaelgermemont/NYC-Blockchain-Devs

**Comment by vutsalsinghal** [comment]
@mickaelgermemont you're a collaborator in NYC-Blockchain-Dev...

**Comment by laveradesign** [comment]
a few projects:
1. referral - earn AC when you refer ppl using referral code  - potentially generated by smart contract
2. wallet - a special wallet which will hold AC ( by earning type) and badges 
where earning type : 1. attend the meetup 2. play faucet 3. build smart contract and etc.
3. validator:
 Create a blog post (smart contract to validate that post exist and has more than 500 world)
 Create a presentation and present on the meetup ( store using linnia storage presentation on the blockchain
Create a sellable product - any thing go 
       example - wordpress extension to receive AC token
                        wallet to convert AC into ETH
                        voting 
                        automatically generate smart contract code
                         framework for testing smart contract
     how to : 
                                 examples : 
                                              how to test smart contract
                                              how to start developer career for blockchain
                                                  and many more
