### ISSUE TITLE
Add slack channel with attendance coin channel to docs

### ISSUE THREAD

**Issue by tesla809** [mickaelgermemont/AttendanceCoin#5]
Lets add the NYC-blockchain-devs to the slack channel with the attendanceCoin channel.

**Comment by mickaelgermemont** [comment]
there is a slack channel#attandence_coin and its integrated with this repo. 
does that solve your issue?

**Comment by tesla809** [comment]
Yup. I guess the issue is to add the slack to the docs. I submitted a pull request to update docs: 
https://github.com/mickaelgermemont/AttendanceCoin/pull/7
